resolver: lts-6.31
packages:
- '.'
- location:
    git: https://github.com/zinfra/amazonka-limited
    commit: 49a7c9b8ba95c71c349b7376003348bc15c0beb7
  extra-dep: true
extra-deps:
- aeson-1.1.1.0
- base-compat-0.9.3
- base-orphans-0.6
- ede-0.2.8.7
- either-4.3.4.1
- exceptions-0.6.1
- mmorph-1.0.9
- prelude-prime-0.1
- querystring-pickle-0.2.0
- trifecta-1.6.2.1
